import "./vacancies.scss";
import HeroSection from "../../sections/HeroSection/HeroSection";
import VacancySection from "../../sections/VacancySection/VacancySection";

const Vacancies = () => {
  const categories = [
    { id: 1, name: "Design and Art" },
    { id: 2, name: "HR and Office Management" },
    { id: 3, name: "Law" },
    { id: 4, name: "IT and Technology" },
    { id: 5, name: "Media and Publishing" },
    { id: 6, name: "Finance" },
    { id: 7, name: "Marketing" },
    { id: 8, name: "Customer Service" },
    { id: 9, name: "Transport" },
    { id: 10, name: "Sales" },
    { id: 11, name: "Industry and Construction" },
    { id: 12, name: "Supply and Logistics" },
    { id: 13, name: "Security" },
    { id: 14, name: "Education" },
    { id: 15, name: "Healthcare" },
    { id: 16, name: "Tourism and Leisure" },
    { id: 17, name: "Agriculture" },
    { id: 18, name: "Hospitality" },
  ];
  const vacancies = [
    {
      id: 1,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Fort Worth, Texas",
    },
    {
      id: 2,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Memphis, Tennessee",
    },
    {
      id: 3,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Sacramento, California",
    },
    {
      id: 4,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "San Jose, California",
    },
    {
      id: 5,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Omaha, Nebraska",
    },
    {
      id: 6,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "San Antonio, Texas",
    },
    /* {
      id: 7,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Las Vegas, Nevada",
    },
    {
      id: 8,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Columbus, Ohio",
    },
    {
      id: 9,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Wichita, Kansas",
    },
    {
      id: 10,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Milwaukee, Wisconsin",
    },
   {
      id: 11,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 12,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Minneapolis, Minnesota",
    },
    {
      id: 13,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "San Diego, California",
    },
    {
      id: 14,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Baltimore, Maryland",
    },
    {
      id: 15,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Nashville, Tennessee",
    },
    {
      id: 16,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Atlanta, Georgia",
    },
    {
      id: 17,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "San Antonio, Texas",
    },
    {
      id: 18,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Oklahoma City, Oklahoma",
    },
    {
      id: 19,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Tucson, Arizona",
    },
    {
      id: 20,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Baltimore, Maryland",
    },
    {
      id: 21,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Memphis, Tennessee",
    },
    {
      id: 22,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Boston, Massachusetts",
    },
    {
      id: 23,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Chicago, Illinois",
    },
    {
      id: 24,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Omaha, Nebraska",
    },
    {
      id: 25,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Tucson, Arizona",
    },
    {
      id: 26,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Kansas City, Missouri",
    },
    {
      id: 27,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Miami, Florida",
    },
    {
      id: 28,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Baltimore, Maryland",
    },
    {
      id: 29,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Fort Worth, Texas",
    },
    {
      id: 30,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "San Antonio, Texas",
    },
    {
      id: 31,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Charlotte, North Carolina",
    },
    {
      id: 32,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "San Antonio, Texas",
    },
    {
      id: 33,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Austin, Texas",
    },
    {
      id: 34,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Boston, Massachusetts",
    },
    {
      id: 35,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "New Orleans, Louisiana",
    },
    {
      id: 36,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Virginia Beach, Virginia",
    },
    {
      id: 37,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Chicago, Illinois",
    },
    {
      id: 38,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "El Paso, Texas",
    },
    {
      id: 39,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Cleveland, Ohio",
    },
    {
      id: 40,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Wichita, Kansas",
    },
    {
      id: 41,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Santa Rosa, California",
    },
    {
      id: 42,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Tucson, Arizona",
    },
    {
      id: 43,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Wichita, Kansas",
    },
    {
      id: 44,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Denver, Colorado",
    },
    {
      id: 45,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "San Diego, California",
    },
    {
      id: 46,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Louisville, Kentucky",
    },
    {
      id: 47,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Detroit, Michigan",
    },
    {
      id: 48,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Cleveland, Ohio",
    },
    {
      id: 49,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "New Orleans, Louisiana",
    },
    {
      id: 50,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Nashville, Tennessee",
    },
    {
      id: 51,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Miami, Florida",
    },
    {
      id: 52,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Boston, Massachusetts",
    },
    {
      id: 53,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Santa Rosa, California",
    },
    {
      id: 54,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Albuquerque, New Mexico",
    },
    {
      id: 55,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Virginia Beach, Virginia",
    },
    {
      id: 56,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Nashville, Tennessee",
    },
    {
      id: 57,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "San Antonio, Texas",
    },
    {
      id: 58,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Memphis, Tennessee",
    },
    {
      id: 59,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Baltimore, Maryland",
    },
    {
      id: 60,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "San Francisco, California",
    },
    {
      id: 61,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Sacramento, California",
    },
    {
      id: 62,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Dallas, Texas",
    },
    {
      id: 63,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Seattle, Washington",
    },
    {
      id: 64,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Atlanta, Georgia",
    },
    {
      id: 65,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Oakland, California",
    },
    {
      id: 66,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Boston, Massachusetts",
    },
    {
      id: 67,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "San Jose, California",
    },
    {
      id: 68,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Columbus, Ohio",
    },
    {
      id: 69,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Philadelphia, Pennsylvania",
    },
    {
      id: 70,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Milwaukee, Wisconsin",
    },
    {
      id: 71,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Charlotte, North Carolina",
    },
    {
      id: 72,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Detroit, Michigan",
    },
    {
      id: 73,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Milwaukee, Wisconsin",
    },
    {
      id: 74,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Memphis, Tennessee",
    },
    {
      id: 75,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Miami, Florida",
    },
    {
      id: 76,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Seattle, Washington",
    },
    {
      id: 77,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Fort Worth, Texas",
    },
    {
      id: 78,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Virginia Beach, Virginia",
    },
    {
      id: 79,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Santa Rosa, California",
    },
    {
      id: 80,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Minneapolis, Minnesota",
    },
    {
      id: 81,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Milwaukee, Wisconsin",
    },
    {
      id: 82,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Wichita, Kansas",
    },
    {
      id: 83,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 84,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "San Jose, California",
    },
    {
      id: 85,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Phoenix, Arizona",
    },
    {
      id: 86,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 87,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Washington, D.C.",
    },
    {
      id: 88,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Kansas City, Missouri",
    },
    {
      id: 89,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Oakland, California",
    },
    {
      id: 90,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Miami, Florida",
    },
    {
      id: 91,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Baltimore, Maryland",
    },
    {
      id: 92,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Albuquerque, New Mexico",
    },
    {
      id: 93,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Louisville, Kentucky",
    },
    {
      id: 94,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Columbus, Ohio",
    },
    {
      id: 95,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Portland, Oregon",
    },
    {
      id: 96,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Oakland, California",
    },
    {
      id: 97,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Omaha, Nebraska",
    },
    {
      id: 98,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Portland, Oregon",
    },
    {
      id: 99,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Tulsa, Oklahoma",
    },
    {
      id: 100,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Minneapolis, Minnesota",
    },
    {
      id: 101,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Fresno, California",
    },
    {
      id: 102,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Kansas City, Missouri",
    },
    {
      id: 103,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 104,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Oklahoma City, Oklahoma",
    },
    {
      id: 105,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Santa Rosa, California",
    },
    {
      id: 106,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Jacksonville, Florida",
    },
    {
      id: 107,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Washington, D.C.",
    },
    {
      id: 108,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Virginia Beach, Virginia",
    },
    {
      id: 109,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Tulsa, Oklahoma",
    },
    {
      id: 110,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Philadelphia, Pennsylvania",
    },
    {
      id: 111,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Detroit, Michigan",
    },
    {
      id: 112,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Austin, Texas",
    },
    {
      id: 113,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Virginia Beach, Virginia",
    },
    {
      id: 114,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Louisville, Kentucky",
    },
    {
      id: 115,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Austin, Texas",
    },
    {
      id: 116,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Denver, Colorado",
    },
    {
      id: 117,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Las Vegas, Nevada",
    },
    {
      id: 118,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Miami, Florida",
    },
    {
      id: 119,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "San Antonio, Texas",
    },
    {
      id: 120,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "El Paso, Texas",
    },
    {
      id: 121,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Denver, Colorado",
    },
    {
      id: 122,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Arlington, Texas",
    },
    {
      id: 123,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Arlington, Texas",
    },
    {
      id: 124,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Minneapolis, Minnesota",
    },
    {
      id: 125,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Omaha, Nebraska",
    },
    {
      id: 126,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Cleveland, Ohio",
    },
    {
      id: 127,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Portland, Oregon",
    },
    {
      id: 128,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Fort Worth, Texas",
    },
    {
      id: 129,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Santa Rosa, California",
    },
    {
      id: 130,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Long Beach, California",
    },
    {
      id: 131,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Fresno, California",
    },
    {
      id: 132,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "San Francisco, California",
    },
    {
      id: 133,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Long Beach, California",
    },
    {
      id: 134,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Sacramento, California",
    },
    {
      id: 135,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Chicago, Illinois",
    },
    {
      id: 136,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Raleigh, North Carolina",
    },
    {
      id: 137,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Boston, Massachusetts",
    },
    {
      id: 138,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Santa Rosa, California",
    },
    {
      id: 139,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Las Vegas, Nevada",
    },
    {
      id: 140,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "New Orleans, Louisiana",
    },
    {
      id: 141,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Denver, Colorado",
    },
    {
      id: 142,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Phoenix, Arizona",
    },
    {
      id: 143,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Charlotte, North Carolina",
    },
    {
      id: 144,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Raleigh, North Carolina",
    },
    {
      id: 145,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Wichita, Kansas",
    },
    {
      id: 146,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Louisville, Kentucky",
    },
    {
      id: 147,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 148,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Oakland, California",
    },
    {
      id: 149,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Santa Rosa, California",
    },
    {
      id: 150,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Washington, D.C.",
    },
    {
      id: 151,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Kansas City, Missouri",
    },
    {
      id: 152,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Philadelphia, Pennsylvania",
    },
    {
      id: 153,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Mesa, Arizona",
    },
    {
      id: 154,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Las Vegas, Nevada",
    },
    {
      id: 155,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 156,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Charlotte, North Carolina",
    },
    {
      id: 157,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Fort Worth, Texas",
    },
    {
      id: 158,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Boston, Massachusetts",
    },
    {
      id: 159,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Raleigh, North Carolina",
    },
    {
      id: 160,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Wichita, Kansas",
    },
    {
      id: 161,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Fresno, California",
    },
    {
      id: 162,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Albuquerque, New Mexico",
    },
    {
      id: 163,
      href: "#",
      src: "#",
      name: "Education Specialist",
      company: "Khan Academy",
      region: "Detroit, Michigan",
    },
    {
      id: 164,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 165,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Wichita, Kansas",
    },
    {
      id: 166,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Colorado Springs, Colorado",
    },
    {
      id: 167,
      href: "#",
      src: "#",
      name: "Sales Specialist",
      company: "Salesforce",
      region: "Miami, Florida",
    },
    {
      id: 168,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "El Paso, Texas",
    },
    {
      id: 169,
      href: "#",
      src: "#",
      name: "Healthcare Specialist",
      company: "Pfizer",
      region: "Washington, D.C.",
    },
    {
      id: 170,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "Oakland, California",
    },
    {
      id: 171,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Seattle, Washington",
    },
    {
      id: 172,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "Cleveland, Ohio",
    },
    {
      id: 173,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Washington, D.C.",
    },
    {
      id: 174,
      href: "#",
      src: "#",
      name: "Hospitality Specialist",
      company: "Hilton",
      region: "Fort Worth, Texas",
    },
    {
      id: 175,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Minneapolis, Minnesota",
    },
    {
      id: 176,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "San Diego, California",
    },
    {
      id: 177,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Nashville, Tennessee",
    },
    {
      id: 178,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Sacramento, California",
    },
    {
      id: 179,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "El Paso, Texas",
    },
    {
      id: 180,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Louisville, Kentucky",
    },
    {
      id: 181,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Raleigh, North Carolina",
    },
    {
      id: 182,
      href: "#",
      src: "#",
      name: "Supply and Logistics Specialist",
      company: "UPS",
      region: "Seattle, Washington",
    },
    {
      id: 183,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Seattle, Washington",
    },
    {
      id: 184,
      href: "#",
      src: "#",
      name: "Law Specialist",
      company: "Baker McKenzie",
      region: "Long Beach, California",
    },
    {
      id: 185,
      href: "#",
      src: "#",
      name: "Design and Art Specialist",
      company: "Adobe",
      region: "Tulsa, Oklahoma",
    },
    {
      id: 186,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Sacramento, California",
    },
    {
      id: 187,
      href: "#",
      src: "#",
      name: "IT and Technology Specialist",
      company: "Google",
      region: "Portland, Oregon",
    },
    {
      id: 188,
      href: "#",
      src: "#",
      name: "Tourism and Leisure Specialist",
      company: "Marriott",
      region: "San Diego, California",
    },
    {
      id: 189,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Tulsa, Oklahoma",
    },
    {
      id: 190,
      href: "#",
      src: "#",
      name: "Security Specialist",
      company: "ADT",
      region: "San Antonio, Texas",
    },
    {
      id: 191,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "Cleveland, Ohio",
    },
    {
      id: 192,
      href: "#",
      src: "#",
      name: "Media and Publishing Specialist",
      company: "Penguin Random House",
      region: "Nashville, Tennessee",
    },
    {
      id: 193,
      href: "#",
      src: "#",
      name: "Industry and Construction Specialist",
      company: "Caterpillar",
      region: "El Paso, Texas",
    },
    {
      id: 194,
      href: "#",
      src: "#",
      name: "Finance Specialist",
      company: "Goldman Sachs",
      region: "Fresno, California",
    },
    {
      id: 195,
      href: "#",
      src: "#",
      name: "Customer Service Specialist",
      company: "Zappos",
      region: "Atlanta, Georgia",
    },
    {
      id: 196,
      href: "#",
      src: "#",
      name: "Marketing Specialist",
      company: "HubSpot",
      region: "Miami, Florida",
    },
    {
      id: 197,
      href: "#",
      src: "#",
      name: "HR and Office Management Specialist",
      company: "LinkedIn",
      region: "Austin, Texas",
    },
    {
      id: 198,
      href: "#",
      src: "#",
      name: "Agriculture Specialist",
      company: "John Deere",
      region: "Memphis, Tennessee",
    },
    {
      id: 199,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Dallas, Texas",
    },
    {
      id: 200,
      href: "#",
      src: "#",
      name: "Transport Specialist",
      company: "FedEx",
      region: "Jacksonville, Florida",
    },*/
  ];
  return (
    <>
      <HeroSection
        categories={categories}
        title={"Find a job"}
        desc={""}
        bg={false}
      />
      <VacancySection vacancies={vacancies} hasButton />
    </>
  );
};
export default Vacancies;
